services:
  backend:
    image: express-ts-devops
    container_name: express-ts-con
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/devops?schema=public
      PORT: 8000
  db:
    image: postgres:13
    container_name: demo-devops-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"