services:
  backend:
    image: 567319031259.dkr.ecr.ap-south-1.amazonaws.com/express-ts-devops:latest
    container_name: express-ts-con
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/devops?schema=public
      PORT: 8000
  db:
    image: postgres:13
    container_name: demo-devops-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local